erudito/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from eruditoapp import views



urlpatterns = [
    path('', include('eruditoapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eruditoapp/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 12 17:20:32 2021

@author: mic5r
"""
from django.urls import path
from eruditoapp import views

app_name= 'eruditoapp'
urlpatterns= [path('about/', views.about, name='about'),
              path('', views.home, name="home"),
              path('subject/', views.subjects, name="subjects"),
              path('subject/<slug:subject_name_slug>/', views.show_subject,
                   name= 'show_subject'),
              path('subject/<slug:subject_name_slug>/<str:sort>', views.show_subject,
                   name= 'show_subject'),
              path("subject/<slug:subject_name_slug>/add_thread/", views.add_thread, name="add_thread"),
              path("subject/<slug:subject_name_slug>/thread/<slug:thread_name_slug>",
                   views.show_thread, name="show_thread"),
              path('register/', views.register, name='register'),
              path('login/', views.user_login, name='login'),
              path('restricted/', views.restricted, name='restricted'),
              path('logout/', views.user_logout, name='logout'),
              path('my-account/', views.my_account, name='my_account'),
              path('register/', views.register, name='register'),
              path('my-account/edit', views.edit_profile, name='edit'),
               path("subject/<slug:subject_name_slug>/thread/<slug:thread_name_slug>/add_comment",
                   views.add_comment, name="add_comment"),
               path('like_comment/', views.LikeCommentView.as_view(), name = 'like_comment'),
               path('like_thread/', views.LikeThreadView.as_view(), name='like_thread'),
               path('user/<slug:user_name_slug>/', views.show_user,
                    name= 'user'),
               path('subject/<slug:subject_name_slug>/useful-resources/',views.useful_resources, name ='useful_resources'),
               path('subject/<slug:subject_name_slug>/search/',views.search_thread, name = 'search'),
              path('subject/<slug:subject_name_slug>/report_thread/<slug:thread_name_slug>',views.report_problem, name='report_thread'),
              path('subject/<slug:subject_name_slug>/report_thread/<slug:thread_name_slug>/<int:comment_id>',views.report_problem, name='report_thread'),
              ]

templates/erudito/about.html
{% extends 'erudito/base.html' %}
{% load staticfiles %}


{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>FAQ</h1>

    <h3> What is this website?</h3>
    <p>This is  Quora/Reddit inspired web application to help high school students
    during COVID find resources for online learning, with a forum page to ask questions on subjects.
    </p>
    <hr>
    <h3> What are some of the features of this website? </h3>
    <p>Features of the website include categories to contain subjects.
    Discussion threads on certain topics of the subjects.
    Pages that can include links to other sites that may be of use to students.
    The ability to rate or flag answers and answerers based on their quality and appropriateness respectively.
    Includes an about page to include information on a guide to the website, FAQ's and contact links to ask questions/give suggestions.
    </p>
    <hr>
    <h3> Who created this website?</h3>
    <p>This website was created by University of Glasgow students: Kyle Buchanan, Michael Lordes Richards
    and James McClure.
    </p>
    <hr>
    <h3>How can I get in contact with the admins for the website for questions and ideas</h3>
    <p>Contact Eruditohelp@gmail.com</p>
    <br>



{% endblock %}

templates/erudito/add_comment.html
{% extends 'erudito/base.html' %}


{% block title_block %}
    Add comment to {{ thread.slug }}
{% endblock %}

{% block body_block %}
    <h1> Add comment </h1>
    <div> 
        <form id="CommentForm" method="POST" action="{% url 'eruditoapp:add_comment' subject.slug thread.slug %}">
            {% csrf_token %}
            {% for field in form %}
                    {{ field.errors }}
                    {{ field.label_tag }} 
                    <div>{{ field }}</div>
                    <br>
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            {% endfor %}
            <input class="btn  btn-secondary fw-bold border-white bg-white" type="submit" name="submit" value="Add comment" />
        </form>
    </div>
{% endblock %}

templates/erudito/add_thread.html
{% extends 'erudito/base.html' %}


{% block title_block %}
    Add thread to {{ subject.name }}
{% endblock %}

{% block body_block %}
    <h1> Add thread to {{ subject.name }} </h1>
    <div> 
        <form id="ThreadForm" method="POST" action="{% url 'eruditoapp:add_thread' subject.slug %}">
            {% csrf_token %}
            {% for field in form %}
                    {{ field.errors }}
                   {{ field.label_tag }} {{ field }}<br>
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
            {% endfor %}
        <br>
            <input class="btn  btn-secondary fw-bold border-white bg-white" type="submit" name="submit" value="Add thread" />
        </form>
    </div>
    <br>
{% endblock %}

templates/erudito/base.html
{% load static %}
<!doctype html>
{% load staticfiles %}
<html lang="en" class="h-100">
<head>

{% block head_block %}
{% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>
        Erudito --
        {% block title_block %}
        {% endblock %}
    </title>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">




    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'erudito/bootstrap_Base.css' %}">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'erudito/custom_Base.css' %}">
</head>

<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">Erudito</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link" aria-current="page" href="{% url 'eruditoapp:home' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'eruditoapp:logout' %}">Log out</a>
                <a class="nav-link" href="{% url 'eruditoapp:my_account' %}">My account</a>
                {% else %}
                <a class="nav-link" href="{% url 'eruditoapp:login' %}">Login</a>
                {% endif %}
                <a class="nav-link" href="{% url 'eruditoapp:subjects' %}">Subjects</a>
                <a class="nav-link" href="{% url 'eruditoapp:about' %}">About</a>
            </nav>
        </div>
    </header>

    {% block body_block %}
    {% endblock %}


</div>
<script src="{% static "javascript/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
<script src="{% static "javascript/feather.js" %}"></script>
<script src="{% static "javascript/erudito-ajax.js" %}"></script>

<script>
    feather.replace()
</script>
</body>


</html>

templates/erudito/edit_profile.html
{% extends 'erudito/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Edit profile
{% endblock %}

{% block body_block %}
<h1>Edit your profile</h1>
    <form id="user_form" method="post"  enctype="multipart/form-data">

        {% for error in user_form.username.errors %}
            <p>{{ error }}</p>
        {% endfor %}

        {% csrf_token %}
         New Username:
        <br>
        <input class="input-look" type="text" name="username" value="" size="50" />
        <br>
        New Email Address:
        <br>
        <input class="input-look" type="email" name="email" value="" size="50" />
        <br>
        New Password:
        <br>
        <input class="input-look" type="password" name="password" value="" size="50" />

        <br>
        <input class="btn btn-secondary fw-bold border-white bg-white" type="submit" name="submit" value="Submit" />
    </form>

{#<div class="container">#}
{#  <form method="post">#}
{#  {% csrf_token %}#}
{#  {{ form.as_p }}#}
{#  <button type="button"><a href={% url 'eruditoapp:password' %}>Change Password</button>#}
{#  <br></br>#}
{#  <button type="submit">Submit</button>#}
{#  </form>#}
{#  <br>#}
{#</div>#}

{% endblock %}

templates/erudito/home.html
{% extends 'erudito/base.html' %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}

    <main class="px-3">
        <h1>Erudito</h1>
        <p class="lead">Erudito is website specifically designed to help high school students with their studies. Choose your subject and start to read forums on certain questions or ask your own questions...</p>
        <p class="lead">
            <a href="{% url 'eruditoapp:about' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
        </p>
        <p> Here are all our subjects</p>
        {% if subjects %}
            {% for subject in subjects %}
                <a class="btn btn-lg btn-secondary fw-bold border-white bg-white" href="{% url 'eruditoapp:show_subject' subject.slug %}" class="subject-text-colour" >{{ subject.name }}</a>
            {% endfor %}
        {% endif %}
    </main>

{% endblock %}

templates/erudito/login.html
{% extends 'erudito/base.html' %}
{% load static %}

{% block title_block %}
    Sign In
{% endblock %}

{% block body_block %}

<body class="text-center">
        <h1>Login</h1>
        <form id="login_form" method="post" action="{% url 'eruditoapp:login' %}">
            {% csrf_token %}
            Username:<br>
            <input class="input-look" type="text" name="username" value="" size="50" />
            <br>
            Password:
            <br>
            <input class="input-look" type="password" name="password" value="" size="50" />
            <br>
            <br>
            <input class="btn  btn-secondary fw-bold border-white bg-white" type="submit" value="Submit" />
        </form>
{% if message %}
<p>{{ message }}</p>
{% endif %}
    <br>
<p class="register-link"> New to Erudito? <a href= "{% url 'eruditoapp:register' %}"> Register here! </a></p>


</body>
{% endblock %}

</html>

templates/erudito/my_account.html
{% extends 'erudito/base.html' %}
{% load static %}


{% block title_block %}
    My Account
    <style>
        component-alignment{
            text-align: unset;
        }
    </style>
{% endblock %}

{% block body_block %}
<div class="my-account-grid">
    <div class="my-account-grid-elements">
        Profile Picture:<br><img src="{{ user.userprofile.picture.url }}" width="240" height="240">
    </div>
    <div class="my-account-grid-elements">
        <br>
        <p>Username: {{ user }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Role: {{ user.userprofile.role }}</P>
        <p>Score: {{ user.userprofile.score}}</p>
    </div>
</div>
    <br>
    <a class="btn btn-lg btn-secondary fw-bold border-white bg-white" href="{% url 'eruditoapp:edit' %}" class="subject-text-colour" >Edit Profile</a>
<div class="container">
  <p> User Created Threads: <p>
    {% for thread in threads %}
        <li> <a href="{% url 'eruditoapp:show_thread' thread.subject.slug thread.slug %}"> {{ thread.title }} -- {{ thread.subject }} </a></li>
    {% endfor %}
</div>
{% endblock %}

templates/erudito/profile.html
{% extends 'erudito/base.html' %}
{% load static %}


{% block title_block %}
    {% if ouser %}
        {{ ouser }}
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="my-account-grid">
        <div class="my-account-grid-elements">
            Profile Picture:<br> <img src="{{ ouser.userprofile.picture.url }}" width="240" height="240">
        </div>
        <div class="my-account-grid-elements">
            <br>
            <p>Username: {{ ouser }}</p>
            <p>Email: {{ ouser.email }}</p>
            <p>Role: {{ ouser.userprofile.role }}</P>
            <p>Score: {{ ouser.userprofile.score}}</p>
        </div>
    </div>
    <br>
<div class="container">
  <p> user created threads <p>
    {% for thread in threads %}
        <li> <a href="{% url 'eruditoapp:show_thread' thread.subject.slug thread.slug %}"> {{ thread.title }} -- {{ thread.subject }} </a></li>
    {% endfor %}
</div>
{% endblock %}

templates/erudito/report.html
{% extends 'erudito/base.html' %}


{% block title_block %}
Report a problem
{% endblock %}

{% block body_block %}
<h1> Report a problem </h1>

{% if subject %}
    {% if thread %}
        {% if comment %}
            Reporting <a href="{% url 'eruditoapp:show_thread' subject.slug thread.slug %}">{{ comment.body|truncatechars:30 }}</a> in
        {% else %}
            Reporting 
        {% endif %}
        thread <a href="{% url 'eruditoapp:show_thread' subject.slug thread.slug %}">{{ thread.title|truncatechars:30 }}</a> in subject <a href="{% url 'eruditoapp:show_subject' subject.slug %}">{{ subject.name|truncatechars:30 }}</a>
    {% endif %}
   
    <form name="report" method="post" action="{% url 'eruditoapp:report_thread' subject.slug thread.slug %}">
     {% csrf_token %}
    <input type="text" name="report_body" placeholder="What's wrong?" />
    <button><a href="{% url 'eruditoapp:report_thread' subject.slug thread.slug %}"></a>Submit</button>
    </form>
{% endif %}
{% endblock %}

templates/erudito/subject.html
{% extends 'erudito/base.html' %}
{% load static %}


{% block title_block %}
    {% if subject %}
        {{ subject.name }}
    {% endif %}
{% endblock %}

{% block body_block %}
    <p>Search for threads here</p>
    <form name="search-bar" method="get" action="{% url 'eruditoapp:search' subject.slug %}" >
        <input type="text" name="search" placeholder="Search" />
        <button class="btn  btn-secondary fw-bold border-white bg-white" href="{% url 'eruditoapp:search' subject.slug %}">Search</button>
    </form>
    <br>
    Sort by:
    <a class="btn  btn-secondary fw-bold border-white bg-white" href= "{% url 'eruditoapp:show_subject' subject.slug '-date' %}">Most Recent</a>
    <a class="btn  btn-secondary fw-bold border-white bg-white" href= "{% url 'eruditoapp:show_subject' subject.slug '-score' %}">Most Popular</a>

    {% if user.is_authenticated %}
        {% for thread, vote in votes %}
        <div>
            <a href="{% url 'eruditoapp:show_thread' subject.slug thread.slug %}" class="btn btn-lg btn-secondary fw-bold border-white subject-thread-presentation">{{ thread.title }}
            <br><p class="subject-thread-body">{{ thread.body|truncatechars:150 }}</p></a><br>
            <strong id="like_count_thread{{ thread.id }}">{{ thread.score }} </strong> likes
            
            
            {% if vote == 'liked' %}
                    <button style="display: none" id= "threadbtn{{ thread.id }}"
                            data-threadid="{{ thread.id }}"
                            class="thread_like_btn btn btn-primary btn-sm"
                            type="button">
    
                        <span data-feather="thumbs-up"></span>
                    </button>
                    <button id="thread_dislike{{ thread.id }}"
                            data-threadid="{{ thread.id }}"
                            class="thread_dislike_btn btn btn-primary btn-sm"
                            type="button">
                            <span data-feather="thumbs-down"></span>
                    </button>
          
            {% else %}
                <button id= "threadbtn{{ thread.id }}"
                            data-threadid="{{ thread.id }}"
                            class="thread_like_btn btn btn-primary btn-sm"
                            type="button">
    
                        <span data-feather="thumbs-up"></span>
                </button>
                <button style="display: none" id="thread_dislike{{ thread.id }}"
                            data-threadid="{{ thread.id }}"
                            class="thread_dislike_btn btn btn-primary btn-sm"
                            type="button">
                            <span data-feather="thumbs-down"></span>
                </button>
                
            {% endif %}
                  
                <a class="btn btn-primary btn-sm" href="{% url 'eruditoapp:report_thread' subject.slug thread.slug %}">
                    <span data-feather="flag"></span>
                </a>

        </div>
            <br>
        {% endfor %}
        <p><a href= "{% url 'eruditoapp:add_thread' subject.slug %}">Add Thread</a></p>




    {% else %}
        {% for thread in threads %}
            <a href="{% url 'eruditoapp:show_thread' subject.slug thread.slug %}" class="btn btn-lg btn-secondary fw-bold border-white subject-thread-presentation">{{ thread.title }}
            <br><p class="subject-thread-body">{{ thread.body|truncatechars:150 }}</p></a><br>
            <strong id="like_count_thread{{ thread.id }}">{{ thread.score }} </strong> likes <br>     
        {% endfor %}
        
        <p> To create a thread or like you must <a href= "{% url 'eruditoapp:login' %}">log in</a></p>
        <p> Don't have an account? <a href= "{% url 'eruditoapp:register' %}">Sign Up</a></p>
    {% endif %}

    <p><a href= "{% url 'eruditoapp:useful_resources' subject.slug %}">Useful Resources</a></p>
    
    <input hidden id="refresh" value="no">
{% endblock %}

templates/erudito/subjects.html
{% extends 'erudito/base.html' %}
{% load static %}


{% block title_block %}
    Subjects
{% endblock %}

{% block body_block %}

    <p id="subject-header">Our available subjects</p>
    
    {% if subjects %}
    <ul>
        {% for subject in subjects %}
            <a class="btn btn-lg btn-secondary fw-bold border-white bg-white" href="{% url 'eruditoapp:show_subject' subject.slug %}" class="subject-text-colour" >{{ subject.name }}</a>
        {% endfor %}
    </ul>
    {% endif %}

    <br/>
    Think we need to add more subjects? Email us at helpSupportErudito@gmail.com if you have any suggestions, we would love to hear them!

{% endblock %}

templates/erudito/thread.html
{% extends 'erudito/base.html' %}
{% load static %}


{% block title_block %}
    {{ thread.title }}
{% endblock %}

{% block body_block %}
    <p><a class= "btn  btn-secondary fw-bold border-white bg-white" href= "{% url 'eruditoapp:show_subject' subject.slug %}"> Back to: {{ subject.name }} </a></p>
    <div>
        <h1> {{ thread.title }} </h1>
        <p><img src="{{ thread.user.userprofile.picture.url }}" width="40" height="40"> <a href= "{% url 'eruditoapp:user' thread.user %}">{{ thread.user }} </a> asks : </p>
        <p>{{ thread.body }}</p>
    </div>
    <div>
    <h1> Comments </h1>
    {% if comments %}
    <ul>
        {% if user.is_authenticated %}
            {% for comment, vote in votes %}
                <p><img src="{{ comment.user.userprofile.picture.url }}" width="40" height="40"><a href= "{% url 'eruditoapp:user' comment.user %}">{{ comment.user }} </a> <p>  {{ comment.body }} </p> </p>
                <div>
                    <strong id="like_count{{ comment.id }}">{{ comment.score }}</strong> likes
                    
                    
                        
                    {% if vote == 'liked' %}
                    <button style= "display: none" id="like_btn{{ comment.id }}"
                                data-commentid="{{ comment.id }}"
                                class="comment_like_btn btn btn-primary btn-sm"
                                type="button">
                            <span data-feather="thumbs-up"></span>
                    </button>
                    
                    <button id="dislike_btn{{ comment.id }}"
                            data-commentid="{{ comment.id }}"
                            class="comment_dislike_btn btn btn-primary btn-sm"
                            type="button">
    
                        <span data-feather="thumbs-down"></span>
                    
    
                    </button>
                    {% else %}
                        <button id="like_btn{{ comment.id }}"
                                data-commentid="{{ comment.id }}"
                                class="comment_like_btn btn btn-primary btn-sm"
                                type="button">
                            <span data-feather="thumbs-up"></span>
                        </button>
                        <button style= "display: none" id="dislike_btn{{ comment.id }}"
                            data-commentid="{{ comment.id }}"
                            class="comment_dislike_btn btn btn-primary btn-sm"
                            type="button">
                        <span data-feather="thumbs-down"></span>
                        </button>
                    
                    {% endif %}
                    <a class="btn btn-primary btn-sm" href="{% url 'eruditoapp:report_thread' subject.slug thread.slug comment.id %}">
                    <span data-feather="flag"></span>
                </a>
                </div>
            {% endfor %}
        {% else %}
            {% for comment in comments %}
                <p><img src="{{ comment.user.userprofile.picture.url }}" width="40" height="40"><a href= "{% url 'eruditoapp:user' comment.user %}">{{ comment.user }} </a> <p>  {{ comment.body }} </p> </p>
                    <strong id="like_count{{ comment.id }}">{{ comment.score }}</strong> likes
            {% endfor %}
            
        {% endif %}
    </ul>
    {% else %}
        There are no comments yet.
    {% endif %}
    </div>
    {% if user.is_authenticated %}
    <p> <a href="{% url 'eruditoapp:add_comment' subject.slug thread.slug %}"> Add Comment! </a></p>
    {% else %}
    <br/>
    <p> To add a comment or like you must <a href= "{% url 'eruditoapp:login' %}">log in</a></p>
    <p> Don't have an account? <a href= "{% url 'eruditoapp:register' %}">Sign Up</a></p>
    {% endif %}
    
    <input hidden id="refresh" value="no">

{% endblock %}

templates/erudito/useful-resources.html
{% extends 'erudito/base.html' %}
{% load static %}

{% block title_block %}
    {% if subject %}
        Resources for {{ subject.name }}
    {% endif %}

{% endblock %}

{% block body_block %}
    Below are the Useful links for {{ subject.name }}:
    <br/>
    {% for resource in resources %}
        <li>{{ resource.body }}: <a href="{{ resource.url }}">{{ resource.url }}</a> </li>
    {% endfor %}

    <br>
    <p>Think we're missing something? Email us at Contact eruditohelp@gmail.com
        for some suggestions.</p>

{% endblock %}